import type { Database, Manufacturer, Product, Customer, Sale, SaleItem } from '../types/database.types';

const now = () => new Date().toISOString();

export const seedManufacturers: Manufacturer[] = [
  {
    id: 1,
    name: 'Apex Footwear Co.',
    contactPerson: 'Riya Desai',
    email: 'riya@apexfootwear.com',
    phone: '9876543210',
    address: '12 Industrial Park, Surat, Gujarat',
    gstin: '24ABCDE1234F1Z5',
    creditLimit: 250000,
    outstandingBalance: 0,
    paymentTerms: 'Net 30',
    notes: 'Primary vendor for casual line',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 2,
    name: 'StrideWorks Manufacturing',
    contactPerson: 'Aman Khanna',
    email: 'aman@strideworks.in',
    phone: '9123456789',
    address: 'B-22, MIDC, Pune, Maharashtra',
    gstin: '27ABCDE1234F1Z6',
    creditLimit: 180000,
    outstandingBalance: 25000,
    paymentTerms: 'Net 15',
    notes: 'Sports footwear supplier',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
];

export const seedProducts: Product[] = [
  {
    id: 1,
    sku: 'FW-CAS-001',
    name: 'Urban Glide Sneakers',
    brand: 'UrbanStep',
    category: 'Casual',
    description: 'Lightweight sneakers for daily wear',
    manufacturerId: 1,
    basePrice: 850,
    sellingPrice: 1099,
    mrp: 1499,
    minStockLevel: 20,
    currentStock: 120,
    imageUrl: '',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 2,
    sku: 'FW-SPR-014',
    name: 'Velocity Runner',
    brand: 'StrideWorks',
    category: 'Sports',
    description: 'Performance running shoes',
    manufacturerId: 2,
    basePrice: 1200,
    sellingPrice: 1599,
    mrp: 1999,
    minStockLevel: 15,
    currentStock: 48,
    imageUrl: '',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
];

export const seedCustomers: Customer[] = [
  {
    id: 1,
    name: 'Arihant Retail',
    businessName: 'Arihant Footwear',
    contactPerson: 'Nikhil Jain',
    email: 'nikhil@arihantfootwear.in',
    phone: '9811122233',
    billingAddress: 'MG Road, Indore, MP',
    shippingAddress: 'MG Road, Indore, MP',
    gstin: '23ABCDE1234F1Z7',
    creditLimit: 100000,
    outstandingBalance: 15000,
    customerType: 'retailer',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
];

export const seedSales: Sale[] = [
  {
    id: 1,
    saleNumber: 'SO-2026-0001',
    customerId: 1,
    saleDate: now(),
    deliveryDate: '',
    subtotal: 3297,
    discountAmount: 0,
    taxAmount: 593.46,
    totalAmount: 3890.46,
    paidAmount: 2000,
    balanceAmount: 1890.46,
    status: 'confirmed',
    notes: 'Initial bulk order',
    createdAt: now(),
    updatedAt: now(),
  },
];

export const seedSaleItems: SaleItem[] = [
  {
    id: 1,
    saleId: 1,
    productId: 1,
    quantity: 2,
    unitPrice: 1099,
    discountPercent: 0,
    discountAmount: 0,
    taxPercent: 18,
    taxAmount: 395.64,
    totalAmount: 2593.64,
    createdAt: now(),
  },
  {
    id: 2,
    saleId: 1,
    productId: 2,
    quantity: 1,
    unitPrice: 1599,
    discountPercent: 0,
    discountAmount: 0,
    taxPercent: 18,
    taxAmount: 197.82,
    totalAmount: 1796.82,
    createdAt: now(),
  },
];

export const seedDatabase = (base: Database): Database => ({
  ...base,
  manufacturers: seedManufacturers,
  products: seedProducts,
  customers: seedCustomers,
  sales: seedSales,
  saleItems: seedSaleItems,
  lastId: {
    ...base.lastId,
    manufacturers: seedManufacturers.length,
    products: seedProducts.length,
    customers: seedCustomers.length,
    sales: seedSales.length,
    saleItems: seedSaleItems.length,
  },
});
